FROM oven/bun:1

WORKDIR /usr/src/app

ARG DATABASE_URL

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/backend ./apps/backend

RUN bun install
RUN DATABASE_URL=${DATABASE_URL} bun run db:generate

EXPOSE 8080
#Commands
CMD ["bun", "run", "start:backend"]


